name: Cucumber + Playwright Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
 cucumber-tests:
  name: Run Cucumber Tests
  runs-on: ubuntu-latest
  timeout-minutes: 30

  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 24

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run Cucumber tests
      run: npm run test:cucumber || true

    - name: Archive Cucumber Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cucumber-report
        path: playwright-report/cucumber.json
        retention-days: 5


  playwright-tests:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: cucumber-tests  # opcional, si quieres que corra después de Cucumber

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:screenplay || true

      - name: Archive Playwright Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/screenplay
          retention-days: 5
